import { CountryData } from "../interfaces";


export const fakeCountries: CountryData[] = [
  {
    nation: "Canada",
    overallScore: 1,
    jameelIndex: '',
    foodIm: 4,
    feedIm: 3,
    forExch: 3,
    supplyReliab: 4,
    supplyRoboost: 1,
    climatePolicy: 2,
    years: [
      {
        year: "2018",
        overallScore: 1,
        jameelIndex: '',
        foodIm: 3,
        feedIm: 5,
        forExch: 2,
        supplyReliab: 4,
        supplyRoboost: 4,
        climatePolicy: 3,
      },
      {
        year: "2019",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 2,
        feedIm: 5,
        forExch: 3,
        supplyReliab: 2,
        supplyRoboost: 2,
        climatePolicy: 4,
      },
      {
        year: "2020",
        overallScore: 1,
        jameelIndex:'',
        foodIm: 5,
        feedIm: 1,
        forExch: 1,
        supplyReliab: 3,
        supplyRoboost:
        
        
        4,
        climatePolicy: 4,
      },
      {
        year: "2021",
        overallScore: 3,
        jameelIndex: '',
        foodIm: 4,
        feedIm: 2,
        forExch: 5,
        supplyReliab: 4,
        supplyRoboost: 3,
        climatePolicy: 3,
      },
      {
        year: "2022",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 1,
        feedIm: 1,
        forExch: 5,
        supplyReliab: 1,
        supplyRoboost: 1,
        climatePolicy: 3,
      },
    ],
  },
  {
    nation: "Germany",
    overallScore: 3,
    jameelIndex: '',
    foodIm: 1,
    feedIm: 3,
    forExch: 4,
    supplyReliab: 3,
    supplyRoboost: 5,
    climatePolicy: 5,
    years: [
      {
        year: "2018",
        overallScore: 1,
        jameelIndex: '',
        foodIm: 4,
        feedIm: 5,
        forExch: 5,
        supplyReliab: 1,
        supplyRoboost: 2,
        climatePolicy: 2,
      },
      {
        year: "2019",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 1,
    feedIm: 3,

        forExch: 4,
        supplyReliab: 1,
        supplyRoboost: 1,
        climatePolicy: 1,
      },
      {
        year: "2020",
        overallScore: 1,
        jameelIndex: '',
        foodIm: 1,
        feedIm: 5,
        forExch: 4,
        supplyReliab: 5,
        supplyRoboost: 4,
        climatePolicy: 2,
      },
      {
        year: "2021",
        overallScore: 3,
        jameelIndex: '',
        foodIm: 1,
        feedIm: 1,
        forExch: 4,
        supplyReliab: 4,
        supplyRoboost: 1,
        climatePolicy: 5,
      },
      {
        year: "2022",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 5,
        feedIm: 5,
        forExch: 3,
        supplyReliab: 5,
        supplyRoboost: 4,
        climatePolicy: 1,
      },
    ],
  },
  {
    nation: "Brazil",
    overallScore: 1,
    jameelIndex: '',
    foodIm: 4,

    feedIm: 2,
    forExch: 1,
    supplyReliab: 3,
    supplyRoboost: 3,
    climatePolicy: 4,
    years: [
      {
        year: "2018",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 2,
        feedIm: 5,
        forExch: 3,
        supplyReliab: 4,
        supplyRoboost: 1,
        climatePolicy: 3,
      },
      {
        year: "2019",
        overallScore: 3,
        jameelIndex: '',
        foodIm: 2,
        feedIm: 5,
        forExch: 4,
        supplyReliab: 3,
        supplyRoboost: 3,
        climatePolicy: 5,
      },
      {
        year: "2020",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 5,
        feedIm: 3,
        forExch: 1,



        supplyReliab: 4,
        supplyRoboost: 3,
        climatePolicy: 1,
      },
      {
        year: "2021",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 4,
        feedIm: 3,


        forExch: 4,
        supplyReliab: 4,
        supplyRoboost: 2,
        climatePolicy: 5,
      },
      {
        year: "2022",
        overallScore: 3,
        jameelIndex:'',
        foodIm: 4,
        feedIm: 3,
        forExch: 2,
        supplyReliab: 4,
        supplyRoboost: 1,
        climatePolicy: 4,
      },
    ],
  },
  {
    nation: "Australia",
    overallScore: 3,
    jameelIndex: '',
    foodIm: 1,
    feedIm: 5,
    forExch: 2,
    supplyReliab: 2,
    supplyRoboost: 5,
    climatePolicy: 3,
    years: [
      {
        year: "2018",
        overallScore: 2,
        jameelIndex: "",
        foodIm: 4,
        feedIm: 4,
        forExch: 2,
        supplyReliab: 5,
        supplyRoboost: 3,
        climatePolicy: 1,
      },
      {
        year: "2019",
        overallScore: 3,
        jameelIndex: '',
        foodIm: 4,
        feedIm: 1,
        forExch: 4,
        supplyReliab: 5,
        supplyRoboost: 4,
        climatePolicy: 5,
      },
      {
        year: "2020",
        overallScore: 2,
        jameelIndex: '',
        foodIm: 4,
        feedIm: 2,
        forExch: 4,
        supplyReliab: 3,
        supplyRoboost: 3,
        climatePolicy: 1,
      },
      {
        year: "2021",
        overallScore: 1,
        jameelIndex: '',
        foodIm: 5,
        feedIm: 3,
        forExch: 2,
        supplyReliab: 2,
        supplyRoboost: 4,
        climatePolicy: 5,
      },
      {
        year: "2022",
        overallScore: 1,
        jameelIndex: '',


        foodIm: 4,
        feedIm: 1,
        forExch: 2,
        supplyReliab: 5,
        supplyRoboost: 5,
        climatePolicy: 1,
      },
    ],
  },

];
