import { CountryData } from "@/components/custom/TableIndex";

export const fakeCountries: CountryData[] = [
  {
    nation: "Canada",
    overallScore: "Very Low",
    jameelIndex: 0.56,
    foodIm: 4,
    feedIm: 3,
    forExch: 3,
    supplyReliab: 4,
    supplyRoboost: 1,
    climatePolicy: 2,
    years: [
      {
        year: "2018",
        overallScore: 'Very Low',
        jameelIndex: 0.17,
        foodIm: 3,
        feedIm: 5,
        forExch: 2,
        supplyReliab: 4,
        supplyRoboost: 4,
        climatePolicy: 3,
      },
      {
        year: "2019",
        overallScore: 'High',
        jameelIndex: 0.11,
        foodIm: 2,
        feedIm: 5,
        forExch: 3,
        supplyReliab: 2,
        supplyRoboost: 2,
        climatePolicy: 4,
      },
      {
        year: "2020",
        overallScore: 'Very Low',
        jameelIndex: 0.44,
        foodIm: 5,
        feedIm: 1,
        forExch: 1,
        supplyReliab: 3,
        supplyRoboost: 4,
        climatePolicy: 4,
      },
      {
        year: "2021",
        overallScore: 'Medium',
        jameelIndex: 0.57,
        foodIm: 4,
        feedIm: 2,
        forExch: 5,
        supplyReliab: 4,
        supplyRoboost: 3,
        climatePolicy: 3,
      },
      {
        year: "2022",
        overallScore: 'High',
        jameelIndex: 0.21,
        foodIm: 1,
        feedIm: 1,
        forExch: 5,
        supplyReliab: 1,
        supplyRoboost: 1,
        climatePolicy: 3,
      },
    ],
  },
  {
    nation: "Germany",
    overallScore: "Medium",
    jameelIndex: 0.93,
    foodIm: 1,
    feedIm: 3,
    forExch: 4,
    supplyReliab: 3,
    supplyRoboost: 5,
    climatePolicy: 5,
    years: [
      {
        year: "2018",
        overallScore: 'Low',
        jameelIndex: 0.8,
        foodIm: 4,
        feedIm: 5,
        forExch: 5,
        supplyReliab: 1,
        supplyRoboost: 2,
        climatePolicy: 2,
      },
      {
        year: "2019",
        overallScore: 'High',
        jameelIndex: 0.59,
        foodIm: 1,
        feedIm: 3,
        forExch: 4,
        supplyReliab: 1,
        supplyRoboost: 1,
        climatePolicy: 1,
      },
      {
        year: "2020",
        overallScore: 'Low',
        jameelIndex: 0.65,
        foodIm: 1,
        feedIm: 5,
        forExch: 4,
        supplyReliab: 5,
        supplyRoboost: 4,
        climatePolicy: 2,
      },
      {
        year: "2021",
        overallScore: 'Medium',
        jameelIndex: 0.18,
        foodIm: 1,
        feedIm: 1,
        forExch: 4,
        supplyReliab: 4,
        supplyRoboost: 1,
        climatePolicy: 5,
      },
      {
        year: "2022",
        overallScore: "Low",
        jameelIndex: 0.24,
        foodIm: 5,
        feedIm: 5,
        forExch: 3,
        supplyReliab: 5,
        supplyRoboost: 4,
        climatePolicy: 1,
      },
    ],
  },
  {
    nation: "Brazil",
    overallScore: "Very Low",
    jameelIndex: 0.98,
    foodIm: 4,
    feedIm: 2,
    forExch: 1,
    supplyReliab: 3,
    supplyRoboost: 3,
    climatePolicy: 4,
    years: [
      {
        year: "2018",
        overallScore: 'High',
        jameelIndex: 0.85,
        foodIm: 2,
        feedIm: 5,
        forExch: 3,
        supplyReliab: 4,
        supplyRoboost: 1,
        climatePolicy: 3,
      },
      {
        year: "2019",
        overallScore: "Medium",
        jameelIndex: 0.32,
        foodIm: 2,
        feedIm: 5,
        forExch: 4,
        supplyReliab: 3,
        supplyRoboost: 3,
        climatePolicy: 5,
      },
      {
        year: "2020",
        overallScore: 'Low',
        jameelIndex: 0.68,
        foodIm: 5,
        feedIm: 3,
        forExch: 1,
        supplyReliab: 4,
        supplyRoboost: 3,
        climatePolicy: 1,
      },
      {
        year: "2021",
        overallScore: 'High',
        jameelIndex: 0.33,
        foodIm: 4,
        feedIm: 3,
        forExch: 4,
        supplyReliab: 4,
        supplyRoboost: 2,
        climatePolicy: 5,
      },
      {
        year: "2022",
        overallScore: 'Medium',
        jameelIndex: 0.77,
        foodIm: 4,
        feedIm: 3,
        forExch: 2,
        supplyReliab: 4,
        supplyRoboost: 1,
        climatePolicy: 4,
      },
    ],
  },
  {
    nation: "Australia",
    overallScore: "Medium",
    jameelIndex: 0.14,
    foodIm: 1,
    feedIm: 5,
    forExch: 2,
    supplyReliab: 2,
    supplyRoboost: 5,
    climatePolicy: 3,
    years: [
      {
        year: "2018",
        overallScore: 'Low',
        jameelIndex: 0.27,
        foodIm: 4,
        feedIm: 4,
        forExch: 2,
        supplyReliab: 5,
        supplyRoboost: 3,
        climatePolicy: 1,
      },
      {
        year: "2019",
        overallScore: 'Medium',
        jameelIndex: 0.48,
        foodIm: 4,
        feedIm: 1,
        forExch: 4,
        supplyReliab: 5,
        supplyRoboost: 4,
        climatePolicy: 5,
      },
      {
        year: "2020",
        overallScore: 'High',
        jameelIndex: 0.52,
        foodIm: 4,
        feedIm: 2,
        forExch: 4,
        supplyReliab: 3,
        supplyRoboost: 3,
        climatePolicy: 1,
      },
      {
        year: "2021",
        overallScore: 'Low',
        jameelIndex: 0.76,
        foodIm: 5,
        feedIm: 3,
        forExch: 2,
        supplyReliab: 2,
        supplyRoboost: 4,
        climatePolicy: 5,
      },
      {
        year: "2022",
        overallScore: "Very Low",
        jameelIndex: 0.63,


        foodIm: 4,
        feedIm: 1,
        forExch: 2,
        supplyReliab: 5,
        supplyRoboost: 5,
        climatePolicy: 1,
      },
    ],
  },

];
